import { expect, test, type APIRequestContext, type Page } from '@playwright/test';

const API_BASE = 'http://localhost:5174/api';

interface Seeded {
  shareToken: string;
  gameId: string;
  studentId: string;
}

async function signInAsTutor(
  page: Page,
  request: APIRequestContext,
  lang = 'en',
): Promise<void> {
  const email = `phase6-${Date.now()}-${Math.random().toString(36).slice(2, 8)}@example.com`;
  const res = await request.post(`${API_BASE}/auth/magic-link`, { data: { email } });
  expect(res.status()).toBe(202);
  const body = (await res.json()) as { ok: true; devMagicLinkUrl?: string };
  expect(body.devMagicLinkUrl).toBeTruthy();
  await page.goto(`/login?lang=${lang}`);
  await page.getByTestId('login-email').fill(email);
  await page.getByTestId('login-submit').click();
  await page.goto(body.devMagicLinkUrl!);
  await page.waitForURL(/\/dashboard/);
}

/**
 * Seeds: a tutor (current session), a student, a lesson with feedback,
 * a game generated by the fake LLM, and assigns it. Returns the share
 * token + game id the student-facing tests use.
 */
async function seedAssignedGame(
  page: Page,
  opts: { studentName: string; gameType: 'FILL_BLANK' | 'TIMED_QUIZ' },
): Promise<Seeded> {
  const csrf = await page.evaluate(() =>
    decodeURIComponent(document.cookie.match(/tutor_csrf=([^;]+)/)?.[1] ?? ''),
  );
  return page.evaluate(
    async ({ csrf, studentName, gameType }) => {
      // 1. Student.
      const sRes = await fetch('/api/students', {
        method: 'POST',
        credentials: 'include',
        headers: { 'content-type': 'application/json', 'x-csrf-token': csrf },
        body: JSON.stringify({ name: studentName }),
      });
      const student = (await sRes.json()) as { id: string; shareToken: string };
      // 2. Lesson.
      const lRes = await fetch('/api/lessons', {
        method: 'POST',
        credentials: 'include',
        headers: { 'content-type': 'application/json', 'x-csrf-token': csrf },
        body: JSON.stringify({
          studentId: student.id,
          occurredAt: new Date(Date.now() - 86_400_000).toISOString(),
          title: 'Phase 6 lesson',
        }),
      });
      const lesson = (await lRes.json()) as { id: string };
      // 3. Feedback.
      await fetch(`/api/lessons/${lesson.id}/feedback`, {
        method: 'PATCH',
        credentials: 'include',
        headers: { 'content-type': 'application/json', 'x-csrf-token': csrf },
        body: JSON.stringify({
          feedbackText:
            'Drill present-tense verb conjugation. The student confused walk/walks.',
        }),
      });
      // 4. Generate game. Use a small pool so the test runs fast.
      const gRes = await fetch(`/api/lessons/${lesson.id}/games`, {
        method: 'POST',
        credentials: 'include',
        headers: { 'content-type': 'application/json', 'x-csrf-token': csrf },
        body: JSON.stringify({ type: gameType, poolSize: 5 }),
      });
      const game = (await gRes.json()) as { id: string };
      // 5. Wait for the generation to complete (poll up to 10s).
      let status = 'GENERATING';
      const deadline = Date.now() + 10_000;
      while (status === 'GENERATING' && Date.now() < deadline) {
        const pRes = await fetch(`/api/games/${game.id}`, { credentials: 'include' });
        const p = (await pRes.json()) as { status: string };
        status = p.status;
        if (status === 'GENERATING') await new Promise((r) => setTimeout(r, 300));
      }
      if (status !== 'DRAFT') {
        throw new Error(`Game stuck in status ${status}`);
      }
      // 6. Assign.
      await fetch(`/api/games/${game.id}/assign`, {
        method: 'POST',
        credentials: 'include',
        headers: { 'content-type': 'application/json', 'x-csrf-token': csrf },
        body: '{}',
      });
      return { shareToken: student.shareToken, gameId: game.id, studentId: student.id };
    },
    { csrf, studentName: opts.studentName, gameType: opts.gameType },
  );
}

test.describe('student plays an assigned FILL_BLANK game (LTR)', () => {
  test('dashboard lists game → student opens → plays to completion → summary', async ({
    page,
    request,
  }) => {
    await signInAsTutor(page, request);
    const seeded = await seedAssignedGame(page, {
      studentName: 'Sara',
      gameType: 'FILL_BLANK',
    });

    // The student opens the dashboard in a fresh context — share token IS the credential.
    const studentPage = await page.context().newPage();
    await studentPage.goto(`/s/${seeded.shareToken}`);
    await expect(studentPage.getByTestId('public-student')).toBeVisible();
    await expect(
      studentPage.getByTestId(`public-student-game-${seeded.gameId}`),
    ).toBeVisible();
    // Phase 12: a fresh game shows the starting level on the dashboard.
    await expect(
      studentPage.getByTestId(`public-student-level-${seeded.gameId}`),
    ).toHaveText(/Level 1/);

    // Click Play.
    await studentPage.getByTestId(`public-student-play-${seeded.gameId}`).click();
    await studentPage.waitForURL(/\/play\//);
    await expect(studentPage.getByTestId('fill-blank-engine')).toBeVisible();
    // Phase 12: the level badge is shown in the engine header (Level 1/5).
    await expect(studentPage.getByTestId('play-level')).toHaveText(/Level 1\/5/);

    // Loop: submit any answer, advance, until summary appears. We
    // don't know the correct answers (the fake LLM seeds random
    // prompts) — we just verify the engine accepts arbitrary input
    // and the lifecycle reaches Summary.
    for (let i = 0; i < 10; i++) {
      const summaryVisible = await studentPage
        .getByTestId('play-summary')
        .isVisible()
        .catch(() => false);
      if (summaryVisible) break;
      const input = studentPage.getByTestId('play-answer-input');
      await expect(input).toBeEnabled();
      await input.fill('answer');
      await studentPage.getByTestId('play-submit').click();
      await expect(studentPage.getByTestId('play-feedback')).toBeVisible();
      await studentPage.getByTestId('play-next').click();
      // Wait for either the feedback to clear (new question loaded) or
      // for the summary to appear (we just finished the last round).
      await Promise.race([
        studentPage.getByTestId('play-feedback').waitFor({ state: 'detached', timeout: 5_000 }),
        studentPage.getByTestId('play-summary').waitFor({ state: 'visible', timeout: 5_000 }),
      ]).catch(() => {});
    }

    await expect(studentPage.getByTestId('play-summary')).toBeVisible({ timeout: 15_000 });
    const score = await studentPage.getByTestId('play-summary').getAttribute('data-score');
    expect(score).not.toBeNull();

    // Best-score badge present.
    await expect(studentPage.getByTestId('play-summary-best')).toBeVisible();
  });

  test('keyboard-only play submits + advances via Enter only', async ({ page, request }) => {
    await signInAsTutor(page, request);
    const seeded = await seedAssignedGame(page, {
      studentName: 'KeyboardSara',
      gameType: 'FILL_BLANK',
    });
    const studentPage = await page.context().newPage();
    await studentPage.goto(`/s/${seeded.shareToken}`);
    await studentPage.getByTestId(`public-student-play-${seeded.gameId}`).click();
    await expect(studentPage.getByTestId('fill-blank-engine')).toBeVisible();
    for (let i = 0; i < 12; i++) {
      const summaryVisible = await studentPage
        .getByTestId('play-summary')
        .isVisible()
        .catch(() => false);
      if (summaryVisible) break;
      const input = studentPage.getByTestId('play-answer-input');
      await expect(input).toBeEnabled();
      await input.focus();
      await studentPage.keyboard.type('typed');
      await studentPage.keyboard.press('Enter');
      await expect(studentPage.getByTestId('play-feedback')).toBeVisible();
      // Pressing Enter on the focused Next button advances.
      await studentPage.keyboard.press('Enter');
      await Promise.race([
        studentPage.getByTestId('play-feedback').waitFor({ state: 'detached', timeout: 5_000 }),
        studentPage.getByTestId('play-summary').waitFor({ state: 'visible', timeout: 5_000 }),
      ]).catch(() => {});
    }
    await expect(studentPage.getByTestId('play-summary')).toBeVisible({ timeout: 15_000 });
  });

  test('viewport sanity: no horizontal scrollbar at 320 / 768 / 1280', async ({
    page,
    request,
  }) => {
    await signInAsTutor(page, request);
    const seeded = await seedAssignedGame(page, {
      studentName: 'Viewport',
      gameType: 'FILL_BLANK',
    });
    const studentPage = await page.context().newPage();
    await studentPage.goto(`/s/${seeded.shareToken}`);
    await studentPage.getByTestId(`public-student-play-${seeded.gameId}`).click();
    await expect(studentPage.getByTestId('fill-blank-engine')).toBeVisible();
    for (const vw of [1280, 768, 320]) {
      await studentPage.setViewportSize({ width: vw, height: 800 });
      const overflow = await studentPage.evaluate(() => ({
        scrollWidth: document.documentElement.scrollWidth,
        clientWidth: document.documentElement.clientWidth,
      }));
      expect(overflow.scrollWidth, `vw=${vw}`).toBeLessThanOrEqual(overflow.clientWidth + 1);
    }
  });
});

test.describe('student plays an assigned TIMED_QUIZ game', () => {
  test('plays until game-over via deterministic timer mocking', async ({ page, request }) => {
    await signInAsTutor(page, request);
    const seeded = await seedAssignedGame(page, {
      studentName: 'Quiz',
      gameType: 'TIMED_QUIZ',
    });
    const studentPage = await page.context().newPage();
    await studentPage.goto(`/s/${seeded.shareToken}`);
    await studentPage.getByTestId(`public-student-play-${seeded.gameId}`).click();
    await expect(studentPage.getByTestId('timed-quiz-engine')).toBeVisible();

    // Three wrong picks should exhaust lives. Pick the LAST choice each
    // time — overwhelmingly likely to be wrong (only 1/4 chance of right).
    // If we get unlucky we'll just play more rounds; the loop is bounded.
    const maxRounds = 30;
    for (let i = 0; i < maxRounds; i++) {
      const summaryVisible = await studentPage
        .getByTestId('play-summary')
        .isVisible()
        .catch(() => false);
      if (summaryVisible) break;
      // Pick the last visible choice; falls back to first if there's only one.
      const choices = await studentPage.locator('[data-testid^="play-choice-"]').count();
      if (choices === 0) break;
      const pick = Math.max(0, choices - 1);
      const choiceBtn = studentPage.getByTestId(`play-choice-${pick}`);
      await expect(choiceBtn).toBeEnabled();
      await choiceBtn.click();
      await expect(studentPage.getByTestId('play-feedback')).toBeVisible();
      await studentPage.getByTestId('play-next').click();
      await Promise.race([
        studentPage.getByTestId('play-feedback').waitFor({ state: 'detached', timeout: 5_000 }),
        studentPage.getByTestId('play-summary').waitFor({ state: 'visible', timeout: 5_000 }),
      ]).catch(() => {});
    }
    await expect(studentPage.getByTestId('play-summary')).toBeVisible({ timeout: 20_000 });
  });
});

test.describe('Hebrew (RTL) play', () => {
  test('engine renders RTL + html dir=rtl + no horizontal overflow', async ({ page, request }) => {
    await signInAsTutor(page, request, 'he');
    const seeded = await seedAssignedGame(page, {
      studentName: 'דניאל',
      gameType: 'FILL_BLANK',
    });
    const studentPage = await page.context().newPage();
    await studentPage.goto(`/s/${seeded.shareToken}?lang=he`);
    await expect(studentPage.locator('html')).toHaveAttribute('dir', 'rtl');
    await expect(studentPage.getByTestId('public-student')).toBeVisible();
    await studentPage.getByTestId(`public-student-play-${seeded.gameId}`).click();
    await expect(studentPage.getByTestId('fill-blank-engine')).toBeVisible();
    for (const vw of [1280, 768, 320]) {
      await studentPage.setViewportSize({ width: vw, height: 800 });
      const overflow = await studentPage.evaluate(() => ({
        scrollWidth: document.documentElement.scrollWidth,
        clientWidth: document.documentElement.clientWidth,
      }));
      expect(overflow.scrollWidth, `vw=${vw}`).toBeLessThanOrEqual(overflow.clientWidth + 1);
    }
    // Free-text input uses dir="auto" so Hebrew is RTL, English is LTR.
    await expect(studentPage.getByTestId('play-answer-input')).toHaveAttribute('dir', 'auto');
  });
});

test.describe('cross-token attempt access', () => {
  test('attempt created with token A returns 404 when patched with token B', async ({
    page,
    request,
  }) => {
    await signInAsTutor(page, request);
    const a = await seedAssignedGame(page, { studentName: 'A', gameType: 'FILL_BLANK' });
    const b = await seedAssignedGame(page, { studentName: 'B', gameType: 'FILL_BLANK' });
    // Start an attempt as student A.
    const started = await request.post(
      `${API_BASE}/s/${a.shareToken}/games/${a.gameId}/attempts`,
      { data: {} },
    );
    expect(started.status()).toBe(201);
    const body = (await started.json()) as { attemptId: string; questions: { id: string }[] };

    // Try to PATCH that attempt via student B's share token.
    const r = await request.patch(`${API_BASE}/s/${b.shareToken}/attempts/${body.attemptId}/answers`, {
      data: { questionId: body.questions[0]!.id, rawAnswer: 'whatever' },
    });
    expect(r.status()).toBe(404);
  });
});
